# 파이토치(PyTorch)

* 페이스북이 초기 루아(Lua) 언어로 개발된 토치(Torch)를 파이썬 버전으로 개발하여 2017년도에 공개
* 초기에 토치(Torch)는 넘파이(NumPy) 라이브러리처럼 과학 연산을 위한 라이브러리로 공개
* 이후 GPU를 이용한 텐서 조작 및 동적 신경망 구축이 가능하도록 딥러닝 프레임워크로 발전시킴
* 파이썬답게 만들어졌고, 유연하면서도 가속화된 계산 속도를 제공

## 파이토치의 주요 특징

- 동적 계산 그래프(Dynamic Computational Graph): 파이토치는 계산 그래프를 생성하고 수정할 수 있는 동적 계산 그래프를 사용. 이는 모델의 복잡한 흐름과 제어 흐름을 쉽게 구현할 수 있도록 도와준다. 이러한 특징은 딥러닝 모델의 구성과 실험 과정에서 유연성을 제공.

- 자동 미분(Automatic Differentiation): 파이토치는 자동 미분 기능을 제공하여 계산 그래프 상에서의 역전파(Backpropagation)를 자동으로 처리. 이를 통해 모델의 가중치 업데이트를 간편하게 수행.

- 쉬운 인터페이스: 파이토치는 직관적이고 쉬운 인터페이스를 제공. PyTorch는 Pythonic한 구문과 함께 다양한 딥러닝 모델을 구성하고 학습시키는 데에 필요한 다양한 기능을 제공.

- GPU 지원: 파이토치는 GPU를 활용하여 딥러닝 모델의 학습과 추론을 가속화할 수 있다. GPU를 사용하면 대용량 데이터와 복잡한 모델에 대한 연산을 더욱 빠르게 처리.

## 파이토치의 구성요소

- `torch`: 메인 네임스페이스, 텐서 등의 다양한 수학 함수가 포함
- `torch.autograd`: 자동 미분 기능을 제공하는 라이브러리
- `torch.nn`: 신경망 구축을 위한 데이터 구조나 레이어 등의 라이브러리
- `torch.multiprocessing`: 병럴처리 기능을 제공하는 라이브러리
- `torch.optim`: SGD(Stochastic Gradient Descent)를 중심으로 한 파라미터 최적화 알고리즘 제공
- `torch.utils`: 데이터 조작 등 유틸리티 기능 제공
- `torch.onnx`: ONNX(Open Neural Network Exchange), 서로 다른 프레임워크 간의 모델을 공유할 때 사용

## 텐서(Tensors)

* 데이터 표현을 위한 기본 구조로 텐서(tensor)를 사용
* 텐서는 데이터를 담기위한 컨테이너(container)로서 일반적으로 수치형 데이터를 저장
* 넘파이(NumPy)의 ndarray와 유사
* GPU를 사용한 연산 가속 가능

In [8]:
import torch

torch.__version__

'2.0.1+cu118'

텐서 초기화와 데이터 타입

In [9]:
x = torch.empty(4, 2) # 텐서를 초기화 하지 않고, 현재 메모리에 있는 임의의 값으로 채운다

print(x)

tensor([[-1.5074e+12,  4.3393e-41],
        [-1.5074e+12,  4.3393e-41],
        [ 4.4842e-44,  0.0000e+00],
        [ 1.7937e-43,  0.0000e+00]])


In [10]:
import numpy as np

x = np.empty([4, 2])

print(x)

[[5.71437037e-316 0.00000000e+000]
 [5.78120283e-316 5.79013159e-316]
 [5.79014423e-316 5.87396860e-316]
 [5.79577184e-316 5.87308481e-316]]


In [11]:
x = torch.rand(4, 2)

print(x)

tensor([[0.9128, 0.1621],
        [0.0532, 0.4353],
        [0.2321, 0.6533],
        [0.4741, 0.4851]])


### PyTorch는 데이터 타입

1. torch.float32 또는 torch.float: 32비트 부동 소수점 숫자를 나타냅니다. 기본적으로 사용되는 데이터 타입입니다.

2. torch.float64 또는 torch.double: 64비트 부동 소수점 숫자를 나타냅니다. 더 정확한 숫자 계산이 필요한 경우에 사용될 수 있습니다.

3. torch.float16 또는 torch.half: 반 정밀도 16비트 부동 소수점 숫자를 나타냅니다. 메모리를 적게 사용하며, 계산 속도도 빠릅니다. 그러나 정확도가 상대적으로 낮을 수 있습니다.

4. torch.int8, torch.int16, torch.int32, torch.int64: 정수 데이터 타입입니다. 각각 8비트, 16비트, 32비트, 64비트 크기를 가집니다.

5. torch.uint8: 8비트 부호 없는 정수 데이터 타입입니다. 0과 255 사이의 값을 가질 수 있습니다.

6. torch.bool: 불리언 데이터 타입으로, True 또는 False 값을 가집니다.

| Data type | dtype | CPU tensor | GPU tensor |
| ------ | ------ | ------ | ------ |
| 32-bit floating point | `torch.float32` or `torch.float` |`torch.FloatTensor` | `torch.cuda.FloatTensor` |
| 64-bit floating point | `torch.float64` or `torch.double` |`torch.DoubleTensor` | `torch.cuda.DoubleTensor` |
| 16-bit floating point | `torch.float16` or `torch.half` |`torch.HalfTensor` | `torch.cuda.HalfTensor` |
| 8-bit integer(unsinged) | `torch.uint8` |`torch.ByteTensor` | `torch.cuda.ByteTensor` |
| 8-bit integer(singed) | `torch.int8` |`torch.CharTensor` | `torch.cuda.CharTensor` |
| 16-bit integer(signed) | `torch.int16` or `torch.short` |`torch.ShortTensor` | `torch.cuda.ShortTensor` |
| 32-bit integer(signed) | `torch.int32` or `torch.int` |`torch.IntTensor` | `torch.cuda.IntTensor` |
| 64-bit integer(signed) | `torch.int64` or `torch.long` |`torch.LongTensor` | `torch.cuda.LongTensor` |

In [13]:
x = torch.zeros(4, 2, dtype = torch.long)

print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [14]:
x = torch.tensor([3,2,3])

print(x)

tensor([3, 2, 3])


In [15]:
x = x.new_ones(2, 4, dtype = torch.double)

print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [16]:
x = torch.randn_like(x, dtype = torch.float)

print(x)

tensor([[ 1.2407,  0.7776,  0.6915, -1.5044],
        [ 0.7121, -0.6655,  0.2651,  0.9731]])


In [17]:
x = torch.randn(5)

print(x)

tensor([ 1.5406,  0.7117,  1.6220, -2.6492, -0.9022])


In [20]:
print(x.size())

torch.Size([5])

torch.Size([5])


torch.Size([5])

In [22]:
ft = torch.FloatTensor([1, 2, 3])

print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [23]:
print(ft.short())
print(ft.long())
print(ft.int())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3])
tensor([1, 2, 3], dtype=torch.int32)


In [24]:
it = torch.IntTensor([1, 2, 3])

print(it)
print(it.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [25]:
print(it.float())
print(it.double())
print(it.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


### cuda tensor

NVIDIA가 만든 병렬 컴퓨팅 플랫폼 및 API 모델로, 보통 '쿠다'라고 발음한다. CUDA 플랫폼은 GPU 의 가상 명령어셋을 사용할 수 있도록 만들어주는 소프트웨어 레이어이며, NVIDIA가 만든 CUDA 코어가 장착된 GPU에서 작동

In [26]:
x = torch.randn(1)

print(x)
print(x.item())
print(x.dtype)

tensor([0.1694])
0.16937993466854095
torch.float32


In [29]:
a  = torch.randn(10000000)

print(a.mean())
print(a.std())

tensor(0.0003)
tensor(1.0002)


In [30]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

print(device)

cuda


### 다차원 텐서 표현

In [31]:
t0 = torch.tensor(0)

print(t0.dim)
print(t0.shape)
print(t0)

<built-in method dim of Tensor object at 0x78f5ee966de0>
torch.Size([])
tensor(0)


In [32]:
t1 = torch.tensor([1,2,3])

print(t1.dim)
print(t1.shape)
print(t1)

<built-in method dim of Tensor object at 0x78f5ee931620>
torch.Size([3])
tensor([1, 2, 3])


In [33]:
t2 = torch.tensor([[1,2,3],
                   [4,5,6]])

print(t2.dim)
print(t2.shape)
print(t2)

<built-in method dim of Tensor object at 0x78f5ee7eb5b0>
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [34]:
t3 = torch.tensor([[[1,2,3],
                   [4,5,6]],
                   [[7,8,9],
                    [10,11,12]]])

print(t3.dim)
print(t3.shape)
print(t3)

<built-in method dim of Tensor object at 0x78f5ee910a40>
torch.Size([2, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


### 텐서의 연산

In [38]:
import math

a = torch.randn(1, 2) * 2 - 1

print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

tensor([[ 0.0625, -4.8824]])
tensor([[0.0625, 4.8824]])
tensor([[ 1., -4.]])
tensor([[ 0., -5.]])
tensor([[ 0.0625, -0.5000]])


In [39]:
b = torch.randn(1, 5) * 3 - 2

print(b)
print(torch.abs(b))
print(torch.ceil(b))
print(torch.floor(b))
print(torch.clamp(b, -1.5, 0.5))

tensor([[-1.7719, -7.1064,  0.0086, -1.8370, -1.2000]])
tensor([[1.7719, 7.1064, 0.0086, 1.8370, 1.2000]])
tensor([[-1., -7.,  1., -1., -1.]])
tensor([[-2., -8.,  0., -2., -2.]])
tensor([[-1.5000, -1.5000,  0.0086, -1.5000, -1.2000]])


In [36]:
print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1, 2, 3, 1, 2, 1])))

tensor([[-1.6377,  2.5245]])
tensor(-1.6377)
tensor(2.5245)
tensor(0.4434)
tensor(2.9431)
tensor(-4.1344)
tensor([1, 2, 3])


In [40]:
x = torch.rand(2, 2)

print(x, '\n')
print(x.max(dim = 0), '\n')
print(x.max(dim = 1))

tensor([[0.7477, 0.1878],
        [0.0727, 0.5813]]) 

torch.return_types.max(
values=tensor([0.7477, 0.5813]),
indices=tensor([0, 1])) 

torch.return_types.max(
values=tensor([0.7477, 0.5813]),
indices=tensor([0, 1]))


In [41]:
x = torch.rand(2, 2)

print(x, '\n')
print(x.min(dim = 0), '\n')
print(x.min(dim = 1))

tensor([[0.8489, 0.5899],
        [0.8846, 0.9912]]) 

torch.return_types.min(
values=tensor([0.8489, 0.5899]),
indices=tensor([0, 0])) 

torch.return_types.min(
values=tensor([0.5899, 0.8846]),
indices=tensor([1, 0]))


In [42]:
x = torch.rand(2, 2)

print(x)

y = torch.rand(2, 2)

print(y)

tensor([[0.6267, 0.0950],
        [0.0976, 0.2560]])
tensor([[0.4700, 0.4148],
        [0.6175, 0.9598]])


In [45]:
print(x + y)
print(torch.add(x, y))

tensor([[1.0967, 0.5098],
        [0.7151, 1.2158]])
tensor([[1.0967, 0.5098],
        [0.7151, 1.2158]])


In [46]:
result = torch.empty(2, 4)
torch.add(x, y, out = result)

print(result)

tensor([[1.0967, 0.5098],
        [0.7151, 1.2158]])


<ipython-input-46-7800548eea53>:2: UserWarning: An output with one or more elements was resized since it had shape [2, 4], which does not match the required output shape [2, 2]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:26.)
  torch.add(x, y, out = result)


`in-place` 방식
  - in-place방식으로 텐서의 값을 변경하는 연산 뒤에는 _''가 붙음
  - `x.copy_(y), x.t_()`

In [47]:
print(x)
print(y)
print()
y.add_(x)
print(y)

tensor([[0.6267, 0.0950],
        [0.0976, 0.2560]])
tensor([[0.4700, 0.4148],
        [0.6175, 0.9598]])

tensor([[1.0967, 0.5098],
        [0.7151, 1.2158]])


In [48]:
print(x)
print(y)
print(x - y)
x.sub_(y)
print(x)
print(torch.sub(x, y))
print(x.sub(y))
print(x.sub(y))

tensor([[0.6267, 0.0950],
        [0.0976, 0.2560]])
tensor([[1.0967, 0.5098],
        [0.7151, 1.2158]])
tensor([[-0.4700, -0.4148],
        [-0.6175, -0.9598]])
tensor([[-0.4700, -0.4148],
        [-0.6175, -0.9598]])
tensor([[-1.5667, -0.9246],
        [-1.3326, -2.1756]])
tensor([[-1.5667, -0.9246],
        [-1.3326, -2.1756]])
tensor([[-1.5667, -0.9246],
        [-1.3326, -2.1756]])


In [49]:
print(x)
print(y)
print(x - y)
x.mul_(y)
print(x)
print(torch.mul(x, y))
print(x.mul(y))
print(x.mul(y))

tensor([[-0.4700, -0.4148],
        [-0.6175, -0.9598]])
tensor([[1.0967, 0.5098],
        [0.7151, 1.2158]])
tensor([[-1.5667, -0.9246],
        [-1.3326, -2.1756]])
tensor([[-0.5155, -0.2115],
        [-0.4416, -1.1670]])
tensor([[-0.5653, -0.1078],
        [-0.3158, -1.4189]])
tensor([[-0.5653, -0.1078],
        [-0.3158, -1.4189]])
tensor([[-0.5653, -0.1078],
        [-0.3158, -1.4189]])


In [50]:
print(x)
print(y)
print(x - y)
x.div_(y)
print(x)
print(torch.div(x, y))
print(x.div(y))
print(x.div(y))

tensor([[-0.5155, -0.2115],
        [-0.4416, -1.1670]])
tensor([[1.0967, 0.5098],
        [0.7151, 1.2158]])
tensor([[-1.6122, -0.7213],
        [-1.1567, -2.3828]])
tensor([[-0.4700, -0.4148],
        [-0.6175, -0.9598]])
tensor([[-0.4285, -0.8136],
        [-0.8635, -0.7894]])
tensor([[-0.4285, -0.8136],
        [-0.8635, -0.7894]])
tensor([[-0.4285, -0.8136],
        [-0.8635, -0.7894]])


torch.svd(z)는 변수 z의 특이값 분해를 출력.
- 특이값 분해는 행렬을 세 개의 행렬로 분해하는 기법으로, A = UΣVT 형태로 분해. U, Σ, V는 각각 특이벡터(U), 대각행렬(Σ), 전치된 특이벡터(VT)

- 이 코드는 주어진 행렬 x와 y를 곱하고, 곱한 결과 행렬 z에 대해 특이값 분해를 수행하여 특이값, 특이벡터, 그리고 전치된 특이벡터를 출력. 특이값 분해는 다양한 응용 분야에서 사용되는 중요한 행렬 분해 기법.

In [51]:
print(x)
print(y, '\n')
print(torch.matmul(x, y))
z = torch.mm(x, y)
print(z, '\n')
print(torch.svd(z))

tensor([[-0.4700, -0.4148],
        [-0.6175, -0.9598]])
tensor([[1.0967, 0.5098],
        [0.7151, 1.2158]]) 

tensor([[-0.8121, -0.7439],
        [-1.3636, -1.4818]])
tensor([[-0.8121, -0.7439],
        [-1.3636, -1.4818]]) 

torch.return_types.svd(
U=tensor([[-0.4791, -0.8778],
        [-0.8778,  0.4791]]),
S=tensor([2.2937, 0.0824]),
V=tensor([[ 0.6914,  0.7224],
        [ 0.7224, -0.6914]]))


### 텐서의 조작

In [54]:
x = torch.Tensor([[1,2], [3, 4]])

print(x)
print(x[0, 0])
print(x[0, 1])
print(x[:, 1])

tensor([[1., 2.],
        [3., 4.]])
tensor(1.)
tensor(2.)
tensor([2., 4.])


https://bigdatadiary0819.tistory.com/60

º 랜덤한 값을 가지는 텐서 생성

1. torch.rand() : 0과 1 사이의 숫자를 균등하게 생성

2. torch.rand_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의

3. torch.randn() : 평균이 0이고 표준편차가 1인 가우시안 정규분포를 이용해 생성

4. torch.randn_like() :  사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의

5. torch.randint() : 주어진 범위 내의 정수를 균등하게 생성

6. torch.randint_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의

7. torch.randperm() : 주어진 범위 내의 정수를 랜덤하게 생성

º 특정한 값을 가지는 텐서 생성

1. torch.arange() : 주어진 범위 내의 정수를 순서대로 생성

2. torch.ones() : 주어진 사이즈의 1로 이루어진 텐서 생성

3. torch.zeros() : 주어진 사이즈의 0으로 이루어진 텐서 생성

4. torch.ones_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의

5. torch.zeros_like() : 사이즈를 튜플로 입력하지 않고 기존의 텐서로 정의

6. torch.linspace() : 시작점과 끝점을 주어진 갯수만큼 균등하게 나눈 간격점을 행벡터로 출력

7. torch.logspace() : 시작점과 끝점을 주어진 갯수만큼 로그간격으로 나눈 간격점을 행벡터로 출력

In [56]:
x = torch.randn(4, 5)
print(x)
print(x.shape)
print(x.size())

tensor([[-0.3176, -2.0319,  1.0487,  1.2362,  0.3174],
        [-0.0304,  0.3164, -1.4078,  0.3863, -0.0255],
        [-0.1510,  0.0580,  0.5081,  0.7865,  0.8618],
        [-0.6381, -0.7910,  1.3286,  1.4702, -0.0450]])
torch.Size([4, 5])
torch.Size([4, 5])


In [57]:
x = torch.randn(4, 5)

print(x)

y = x.view(20)

print(y)

z = x.view(5, -1)

print(z)

tensor([[-1.3880, -0.9319,  1.4450,  0.5179,  1.0982],
        [ 1.0983, -0.7234,  0.4946, -0.5233, -1.7881],
        [ 1.9823,  0.0410, -0.2324, -0.0920,  0.6743],
        [ 0.4260,  0.0114,  1.7597,  0.6139, -1.4378]])
tensor([-1.3880, -0.9319,  1.4450,  0.5179,  1.0982,  1.0983, -0.7234,  0.4946,
        -0.5233, -1.7881,  1.9823,  0.0410, -0.2324, -0.0920,  0.6743,  0.4260,
         0.0114,  1.7597,  0.6139, -1.4378])
tensor([[-1.3880, -0.9319,  1.4450,  0.5179],
        [ 1.0982,  1.0983, -0.7234,  0.4946],
        [-0.5233, -1.7881,  1.9823,  0.0410],
        [-0.2324, -0.0920,  0.6743,  0.4260],
        [ 0.0114,  1.7597,  0.6139, -1.4378]])


In [58]:
x = torch.randn(1)

print(x)
print(x.item())
print(x.dtype)

tensor([-0.0015])
-0.0015028199413791299
torch.float32


In [59]:
tensor = torch.rand(1, 3, 3)

print(tensor)
print(tensor.shape)

tensor([[[0.8401, 0.8989, 0.8766],
         [0.5992, 0.2973, 0.6941],
         [0.8900, 0.6278, 0.2582]]])
torch.Size([1, 3, 3])


In [61]:
t = tensor.squeeze()
print(t)
print(t.shape)

tensor([[0.8401, 0.8989, 0.8766],
        [0.5992, 0.2973, 0.6941],
        [0.8900, 0.6278, 0.2582]])
torch.Size([3, 3])


In [62]:
tensor.squeeze(dim = 2)

tensor([[[0.8401, 0.8989, 0.8766],
         [0.5992, 0.2973, 0.6941],
         [0.8900, 0.6278, 0.2582]]])

In [64]:
torch.Size([1, 3, 3])

torch.Size([1, 3, 3])

In [65]:
tensor = tensor.unsqueeze(dim =2)

print(tensor)
print(tensor.shape)

tensor([[[[0.8401, 0.8989, 0.8766]],

         [[0.5992, 0.2973, 0.6941]],

         [[0.8900, 0.6278, 0.2582]]]])
torch.Size([1, 3, 1, 3])


tensor.unsqueeze(dim=2)

- unsqueeze 함수는 텐서에 새로운 차원을 추가. 여기서 dim=2는 새로운 차원이 추가될 위치를 나타내며 기존 텐서의 모든 차원의 인덱스를 증가시키고, 새로운 차원은 dim=2에 위치.

- 원래 텐서의 모양(shape)이 (3, 4)이었다면, unsqueeze(dim=2)를 적용한 후의 모양은 (3, 4, 1)이 됩니다. 따라서, 이 코드에서는 기존 텐서에 1차원을 추가

stack은 새로운 차원을 추가하여 텐서들을 결합하는 반면, cat은 기존 차원을 따라 텐서들을 연결

- stack : 새로운 차원이 추가되며, 해당 차원의 크기는 결합할 텐서들의 개수
- cat: 주어진 텐서들을 기존 차원을 따라 연결하여 결합

In [66]:
x = torch.FloatTensor([1, 4])
print(x)

y = torch.FloatTensor([2, 5])
print(y)

z = torch.FloatTensor([3, 6])
print(z)

print(torch.stack([x, y, z]))

tensor([1., 4.])
tensor([2., 5.])
tensor([3., 6.])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [67]:
a = torch.randn(1, 3, 3)
print(a)

b = torch.randn(1, 3, 3)
print(b)

print()

c = torch.cat((a, b), dim = 0)

print(c)

tensor([[[-0.5020, -0.6442, -1.7387],
         [-0.3988, -0.4855,  0.8021],
         [ 0.0817, -0.2299,  1.1314]]])
tensor([[[ 0.6989, -0.6368,  0.8360],
         [ 0.2832,  0.3402, -1.0117],
         [ 1.1777, -0.5233,  0.8390]]])

tensor([[[-0.5020, -0.6442, -1.7387],
         [-0.3988, -0.4855,  0.8021],
         [ 0.0817, -0.2299,  1.1314]],

        [[ 0.6989, -0.6368,  0.8360],
         [ 0.2832,  0.3402, -1.0117],
         [ 1.1777, -0.5233,  0.8390]]])


In [71]:
c = torch.cat((a, b), dim = 1)

print(c)


tensor([[[-0.5020, -0.6442, -1.7387],
         [-0.3988, -0.4855,  0.8021],
         [ 0.0817, -0.2299,  1.1314],
         [ 0.6989, -0.6368,  0.8360],
         [ 0.2832,  0.3402, -1.0117],
         [ 1.1777, -0.5233,  0.8390]]])


In [72]:
tensor = torch.rand(3, 6)
print(tensor)

t1, tw = torch.chunk(tensor, 2, dim = 1)

print(t1, t1.shape)
print(t2)

tensor([[0.1683, 0.2039, 0.1610, 0.3293, 0.2721, 0.0858],
        [0.4576, 0.2405, 0.0457, 0.1307, 0.2856, 0.8656],
        [0.8808, 0.1232, 0.1532, 0.4321, 0.1860, 0.3039]])
tensor([[0.1683, 0.2039, 0.1610],
        [0.4576, 0.2405, 0.0457],
        [0.8808, 0.1232, 0.1532]]) torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [73]:
tensor = torch.rand(3, 6)

t1, t2, t3 = torch.split(tensor, 2, dim = 1)

print(tensor)
print(t1, t1.shape)
print(t2)
print(t3)

tensor([[0.4800, 0.4324, 0.9837, 0.6288, 0.1174, 0.7678],
        [0.9205, 0.3866, 0.8577, 0.8356, 0.2755, 0.5882],
        [0.6236, 0.4139, 0.4826, 0.9802, 0.3698, 0.8920]])
tensor([[0.4800, 0.4324],
        [0.9205, 0.3866],
        [0.6236, 0.4139]]) torch.Size([3, 2])
tensor([[0.9837, 0.6288],
        [0.8577, 0.8356],
        [0.4826, 0.9802]])
tensor([[0.1174, 0.7678],
        [0.2755, 0.5882],
        [0.3698, 0.8920]])
